/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package disastertwitter;

/**
 *
 * @author jpfni
 */
public class GUI extends javax.swing.JPanel {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(null);

        jTextField1.setText("geolocationText");
        add(jTextField1);
        jTextField1.setBounds(340, 110, 181, 29);

        jTextField2.setText("radiusText");
        add(jTextField2);
        jTextField2.setBounds(340, 180, 181, 29);

        jLabel1.setText("geolocation Label");
        add(jLabel1);
        jLabel1.setBounds(127, 111, 145, 23);

        jLabel2.setText("radiusLabel");
        add(jLabel2);
        jLabel2.setBounds(127, 159, 95, 23);
        add(jScrollPane1);
        jScrollPane1.setBounds(877, 108, 932, 539);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/disastertwitter/Background.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 0, 1810, 1200);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
