/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package disastertwitter;

/**
 *
 * @author jpfni
 */
public class GUI extends javax.swing.JPanel {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        geolocationText = new javax.swing.JTextField();
        radiusText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchButton = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1920, 1200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        geolocationText.setNextFocusableComponent(radiusText);
        geolocationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geolocationTextActionPerformed(evt);
            }
        });
        add(geolocationText, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 440, 80));

        radiusText.setNextFocusableComponent(jScrollPane1);
        radiusText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiusTextActionPerformed(evt);
            }
        });
        add(radiusText, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 440, 70));

        jScrollPane1.setBackground(new java.awt.Color(51, 255, 255));
        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 230, 1600, 680));
        add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 640, 670, 260));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/disastertwitter/Background.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void radiusTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiusTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiusTextActionPerformed

    private void geolocationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geolocationTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_geolocationTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField geolocationText;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField radiusText;
    private javax.swing.JLabel searchButton;
    // End of variables declaration//GEN-END:variables
}
